---
- name: configure SOE
  hosts: all
  become: true
  vars:
    - system_owner: mustafizr1122@example.com
  tasks:
    - name: configure /etc/motd
      template:
        src: motd.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: 0644